steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia-south2-docker.pkg.dev/reliable-cairn-438504-g7/quickstart-docker-repo/my-service', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-south2-docker.pkg.dev/reliable-cairn-438504-g7/quickstart-docker-repo/my-service']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    [
      'run', 'deploy', 'shripawandev-adk',
      '--image', 'asia-south2-docker.pkg.dev/reliable-cairn-438504-g7/quickstart-docker-repo/my-service',
      '--region', 'europe-west1',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]
