options:
  logging: CLOUD_LOGGING_ONLY  # This directs logs to Cloud Logging only

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia-south2-docker.pkg.dev/reliable-cairn-438504-g7/shri-pawandev-adk/my-service', '.']

images:
- 'asia-south2-docker.pkg.dev/reliable-cairn-438504-g7/shri-pawandev-adk/my-service'