# ✅ REQUIRED: Logging option to fix service account error
options:
  logging: CLOUD_LOGGING_ONLY  # or use NONE if you prefer

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south2-docker.pkg.dev/reliable-cairn-438504-g7/quickstart-docker-repo/my-service', '.']

images:
  - 'asia-south2-docker.pkg.dev/reliable-cairn-438504-g7/quickstart-docker-repo/my-service'
